### ISSUE TITLE
SetContent fire twice if using InitialEditable()

### ISSUE THREAD

**Issue by ewelinaprus** [vtfuture/BForms#229]
I need to load editable panel but my form is saved two times if I use .InitialEditable() method. Everything is OK if I start in read-only mode. The same problem I found in your UserProfile form.

**Comment by cristipufu** [comment]
Hello @ewelinaprus,

I can't reproduce this. How did u figure out it's saved 2 times ?

**Comment by ewelinaprus** [comment]
I set breakpoint with Visual Studio 2012 on the beggining SetContent() in UserProfileController and then I load Examples/UserProfile page. On the bottom of page in last panel I changed e-mail value and press Save button finally. The breakpoint fired two times. On my own project with PetaPoco ORM my form saved two times and I get two records in my DB. If I remove InitialEditable() from my form everything works fine, but I need to load form in editable mode.
