### ISSUE TITLE
form array parameters not passed to server

### ISSUE THREAD

**Issue by honibis** [vtfuture/BForms#232]
Hi,
Thanks for this wonderful work, decided to use it in our new enterprise content management system project. But have little issues and would be pleased if you can help.

When i use array parameters in BsBeginForm only the first element of array is returned to the server.
While using regular mvc forms if you define editables for the same id its passed as array to the server.

Best Regards,
Ali

**Comment by stefanprodan** [comment]
Can you please provide an example of how you're using BsBeginForm

**Comment by honibis** [comment]
it turns out if i use name convention like this the problem is solved:
name="arrayproperty[@idIndex++]"

Now the thing is my model is an array and type of the property is dynamic. I think i cant use annotations to use BsInputFor. What i need is defining the data type in the BsInputFor func. Imay write an additional function to your source code but that will make version upgrades problematic. Any suggestions?

Regards
