### ISSUE TITLE
What will the theme support in the future?

### ISSUE THREAD

**Issue by mstfcck** [vtfuture/BForms#251]
BForms is really succesfull but What will the theme support in the future? The current theme is not enough. I wanted to use Metronic theme (http://www.keenthemes.com/preview/metronic/). But that is not possible like for now. 

What do you think about that? 

Thanks...

**Comment by oanamangiurea** [comment]
We are not planning to extend the current theme system in the future. You can use other themes on top of BForms but some overriding will be necessary.
