### ISSUE TITLE
Grid bulk actions check box doesn't show buttons Reset,Enabled, disabled, Delete on checkbox click

### ISSUE THREAD

**Issue by iswariya7** [vtfuture/BForms#257]
@(
 Html.BsGridFor(m => m.Grid)
.GridResetButton()
    .ConfigureBulkActions(bulk =>
    {
bulk.AddAction().StyleClass("btn-success js-btn-recommend_selected").Title("Recommend selected").GlyphIcon(Glyphicon.ThumbsUp);
        bulk.AddAction().StyleClass("btn-warning js-btn-unrecommend_selected").Title("Unrecommend selected").GlyphIcon(Glyphicon.ThumbsDown);
        bulk.AddAction(BsBulkActionType.Delete);

        bulk.AddSelector(BsBulkSelectorType.All);
        bulk.AddSelector().StyleClass("js-actives").Text("Recomended");
        bulk.AddSelector().StyleClass("js-inactives").Text("Unrecommended");
        bulk.AddSelector(BsBulkSelectorType.None);

        bulk.ForSelector(BsBulkSelectorType.All).Text("All");
        bulk.ForSelector(BsBulkSelectorType.None).Text("None");
     })

<script type="text/javascript">

    require([
        'bforms-grid'
    ], function () {
        $('#grid').bsGrid({
            uniqueName: 'moviesGrid',
            pagerUrl: this.options.pagerUrl
        });
    });

</script>

**Comment by stefanprodan** [comment]
Please take a look at the demo site where this function is working properly https://github.com/vtfuture/BForms/tree/master/BForms.Docs

**Comment by iswariya7** [comment]
How could i down and run the above in Visual Studio ??

**Comment by stefanprodan** [comment]
https://github.com/vtfuture/BForms/archive/master.zip
