### ISSUE TITLE
Error encountered while pushing to the remote repository: Response status code does not indicate success: 403 (Forbidden)

### ISSUE THREAD

**Issue by stantoxt** [vtfuture/BForms#261]
About Visual Studio git , when I Sync , it occured that Error encountered while pushing to the remote repository: Response status code does not indicate success: 403 (Forbidden).

**Comment by stefanprodan** [comment]
How is this an issue of BForms?

You can't push because your not on the BForms team, make a fork of the project and then a pull request if you made changes.

**Comment by stantoxt** [comment]
At first thanks to you stefanprodan very much, I am also very sorry to admit this problem.You help me too much.Thanks again.
