### ISSUE TITLE
Custom validation on BsDateTime field

### ISSUE THREAD

**Issue by ewelinaprus** [vtfuture/BForms#270]
Hello,
I use custom validation on many fields in my model, but usually with string and some numeric types.
Now I want to use them on BsDateTime field or another Bs* field, but I found some error:

_"Validation type names in unobtrusive client validation rules must be unique."._

How cant I fix it?

With my best,
Ewelina

**Comment by ewelinaprus** [comment]
I found some solution with yield break on TextValue property, but I have found further problems too... My ModelState.GetErrors() returns error for field new_date, but on my partial view there are new_date.TextValue and new_date.DateValue only. I guess that is some problem with binding error to field because of names (new_date and new_date.TextValue).

**Comment by mariuscosareanu** [comment]
Hi,
You can use the second argument of the ValidationResult constructor, e.g:
```
return new ValidationResult(Resx.ErrorMessage, new List<string> { "TextValue" });
```

**Comment by ewelinaprus** [comment]
It works! Thanks a lot! :)

**Comment by ewelinaprus** [comment]
I have one more question: What can I do with RadioButtonList or another BsSelectList? How to show validation message on the field?
