### ISSUE TITLE
Caching of JavaScript Files

### ISSUE THREAD

**Issue by meister-d** [vtfuture/BForms#272]
Hi BForms Team
another Question which came up while Deploying the Application:

Is there a possibility not to have the javascript files cached by the browser?
If I deploy my application with modified js Files, some Users still have the old js Files loaded and run into Errors. What would be the best way to do this without having the User to Clear its Browser Cache?

Regards Dumitru

**Comment by cristipufu** [comment]
Hi Dumitru,

You can add url arguments to your scripts via `RequireJsSetup`:

```cs
@Html.RenderRequireJsSetup(new RequireRendererConfiguration
{
            ....
            UrlArgs = Helpers.GetAppVersion(),
            ....
 })
```

For example, you can set the `UrlArgs` param as the assembly version, so each time you publish your app, the users browsers will force the scripts to refresh.

```cs
public static string GetAppVersion()
{
      return System.Reflection.Assembly.GetExecutingAssembly().GetName().Version.ToString();
}
```

**Comment by meister-d** [comment]
Thanx Cristi
i will give it a try tomorrow morning ;-)

Regards Dumitru
